name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  permissions:
    contents: read

  jobs:
    test:
      runs-on: ubuntu-24.04
      timeout-minutes: 10
      steps:
        - name: Checkout source
          uses: actions/checkout@v7
          with:
            persist-credentials: false

        - name: Set up Java
          uses: actions/setup-java@v6
          with:
            distribution: temurin
            java-version: '21'

        - name: Build and test
          run: ./mnw --batch-mode --no-transfer-progress clean verify
